[build]
  publish = "."

[[headers]]
  for = "/releases/*.apk"
  [headers.values]
    Content-Type = "application/vnd.android.package-archive"
    Content-Disposition = "attachment"
    X-Content-Type-Options = "nosniff"
